version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - my-network

  # Aquí iría tu configuración del backend

networks:
  my-network:
    driver: bridge