version: '3.8'

services:
  frontend:
    image: nginx:alpine
    ports:
      - "4200:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - tfg-network

  spring:
    build: ./spring-backend
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/midb
      SPRING_DATASOURCE_USERNAME: teresa
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure
    networks:
      - tfg-network


  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: midb
      MYSQL_USER: teresa
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - tfg-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: teresa
      PMA_PASSWORD: 1234
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - tfg-network

networks:
  tfg-network:
    driver: bridge

volumes:
  mysql-data:
