version: '3.9'

services:
  backend:
    build: ./backend
    container_name: mi-tfg-spring
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/PlanSync
    networks:
      - my_network

  frontend:
    build: ./frontend
    container_name: mi-tfg-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - my_network

  mongodb:
    image: mongo:latest
    container_name: mi-tfg-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - my_network

  nodeapi:
      build:
        context: ./nodeapi
      ports:
        - "4000:4000"
      depends_on:
        - mongodb
      networks:
        - my_network

volumes:
  mongo_data:

networks:
  my_network:
    driver: bridge
